# Bouclette kiosk key bindings

TAB         cycle pause
PGUP        add chapter -1
PGDWN       add chapter 1
VOLUME_UP   run "/usr/local/bin/bouclette-cec-volume.sh" "up"
VOLUME_DOWN run "/usr/local/bin/bouclette-cec-volume.sh" "down"
